-- Q1. What is the total number of purchases made by customers?
SELECT COUNT(*) AS total_purchases
FROM customer;
-- Q2. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(`Purchase Amount USD`) AS revenue
FROM customer
GROUP BY gender;
-- Q3. What is the average, minimum, and maximum purchase amount?
SELECT 
    AVG(`Purchase Amount USD`) AS avg_amount,
    MIN(`Purchase Amount USD`) AS min_amount,
    MAX(`Purchase Amount USD`) AS max_amount
FROM customer;
-- Q4. Which location has the highest number of customers?
SELECT location, COUNT(*) AS customer_count
FROM customer
GROUP BY location
ORDER BY customer_count DESC;

-- Q5. Which season has the highest purchase volume?
SELECT season, COUNT(*) AS total_purchases
FROM customer
GROUP BY season
ORDER BY total_purchases DESC;

-- Q6. Which product size is most preferred by customers?
SELECT size, COUNT(*) AS total_orders
FROM customer
GROUP BY size
ORDER BY total_orders DESC;

-- Q7. Does discount application affect purchase amount?
-- Compare average purchase amounts:
 SELECT 
    `Discount Applied`,
    AVG(`Purchase Amount USD`) AS avg_spending
FROM customer
GROUP BY `Discount Applied`
ORDER BY avg_spending DESC;
-- Q8. Which payment method is most commonly used?
SELECT 
    `Payment method`, 
    COUNT(*) AS usage_count
FROM customer
GROUP BY `Payment method`
ORDER BY usage_count DESC;

-- Q9. Are subscribers spending more than non-subscribers?
SELECT 
    `Subscription Status`,
    AVG(`Purchase Amount USD`) AS avg_amount
FROM customer
GROUP BY `Subscription Status`;

-- Q10. What is the average review rating by season?
SELECT 
    `Season`,
    AVG(`Ratings`) AS avg_rating
FROM customer
GROUP BY `Season`
ORDER BY avg_rating DESC;

-- Q11. Which colors are most frequently ordered?
SELECT 
    `Color`,
    COUNT(*) AS total_orders
FROM customer
GROUP BY `Color`
ORDER BY total_orders DESC;

-- Q12. Who are high-value customers (purchase amount > average)?
SELECT *
FROM customer
WHERE `Purchase Amount USD` > (
    SELECT AVG(`Purchase Amount USD`) FROM customer
)
ORDER BY `Purchase Amount USD` DESC;

-- Q13. What is the average purchase frequency (days) of customers?
SELECT 
    AVG(`Frequency of Purchases`) AS avg_frequency
FROM customer;

-- Q14. Segment customers into New, Returning, and Loyal based on their total
-- -- number of previous purchased and show the count of each segment.
WITH customer_type AS (
    SELECT 
        `Customer ID`,
        `Previous Purchased`,
        CASE 
            WHEN `Previous Purchased` = 1 THEN 'New'
            WHEN `Previous Purchased` BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT 
    customer_segment,
    COUNT(*) AS `Number of Customers`
FROM customer_type
GROUP BY customer_segment;







